{% set name = "pytorch_revgrad" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytorch_revgrad-{{ version }}.tar.gz
  sha256: 9cf097a7d18cbadddeaec9fef74b258d70b6cb8d0c77f524baab18bffc7d7be9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit
    - numpy
    - pip
    - pytorch >=1.0.0
  run:
    - python >={{ python_min }}
    - numpy
    - pytorch >=1.0.0

test:
  imports:
    - pytorch_revgrad
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/janfreyberg/pytorch-revgrad
  summary: A pytorch module (and function) to reverse gradients.
  license: MIT
  license_file:
    - LICENSE.md
    - LICENSE

extra:
  recipe-maintainers:
    - BastianZim
